# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isubscribe', '0002_auto_20161007_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='status',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'warning'), (2, 'critical')], max_length=3),
        ),
    ]
