# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 10:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isubscribe', '0003_auto_20161007_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='status',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'warning'), (2, 'critical')]),
        ),
    ]
