# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isubscribe', '0005_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='slack_uid',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='status',
            field=models.IntegerField(choices=[(0, 'okay'), (1, 'warning'), (2, 'critical')]),
        ),
    ]
