# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isubscribe', '0006_auto_20161012_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='slack_uid',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
