# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isubscribe', '0007_auto_20161012_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmedia',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='contactmedia',
            name='type',
        ),
        migrations.DeleteModel(
            name='ContactMedia',
        ),
        migrations.DeleteModel(
            name='MediaType',
        ),
    ]
