# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 22:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isubscribe', '0009_auto_20161106_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phonenumber', message="Phone number must contain numbers only: '999999999'. Up to 15 digits allowed.", regex='^\\d{9,15}$')]),
        ),
    ]
